apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
  labels:
    app: weapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: chaitannyaa/my-webapp:v-3
        ports:
        - containerPort: 8501
