apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
  namespace: test-ns
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      targetPort: 8501
  type: ClusterIP
